import React, { useState } from 'react';
import { HelpCircle, ChevronDown, ChevronUp, ShieldCheck, Zap, Award } from 'lucide-react';

export const FaqPage: React.FC = () => {
  const [openIdx, setOpenIdx] = useState<number | null>(0);

  const faqs = [
    {
      q: 'What is the difference between Net Metering, Net Accounting, and Net Plus in Sri Lanka?',
      a: (
        <div className="space-y-2 text-xs text-slate-600 leading-relaxed">
          <p>The Ceylon Electricity Board (CEB) and LECO offer three distinct rooftop solar schemes:</p>
          <ul className="list-disc list-inside space-y-1.5 pl-2">
            <li>
              <b>Net Metering:</b> Solar generation directly offsets your consumption unit-for-unit (1:1 kWh). If generation exceeds consumption in a billing cycle, the surplus is banked as kilowatt-hour energy credits for up to 10–20 years. <i>No monetary cash payout is made.</i>
            </li>
            <li>
              <b>Net Accounting (Most Popular):</b> Solar offsets your consumption. If generation exceeds consumption, the net exported electricity is purchased by the utility in cash at <b>44.14 LKR/kWh</b> (for systems ≤ 20 kW). If you consume more than you generate, you pay only for the net import under standard PUCSL tariffs.
            </li>
            <li>
              <b>Net Plus:</b> 100% of the electricity generated by the solar PV array is fed into the grid and paid in cash at <b>44.14 LKR/kWh</b>. Your domestic household electricity is imported through a separate meter and billed at standard retail domestic rates.
            </li>
          </ul>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 pt-2">
            <div className="p-2.5 bg-slate-50 rounded-xl border border-slate-200 text-center space-y-1">
              <img src="/images/solar meter.png" alt="CEB Bi-Directional Net Meter" className="h-28 mx-auto object-contain" />
              <span className="text-[10px] font-bold text-slate-800 block">CEB Bi-Directional Net Meter</span>
              <span className="text-[9px] text-slate-500 block">Measures both import (from grid) and export (to grid)</span>
            </div>
            <div className="p-2.5 bg-slate-50 rounded-xl border border-slate-200 text-center space-y-1">
              <img src="/images/distruvition meter.png" alt="Main Service Distribution Panel" className="h-28 mx-auto object-contain" />
              <span className="text-[10px] font-bold text-slate-800 block">Service Distribution Panel</span>
              <span className="text-[9px] text-slate-500 block">Connects inverter AC output to household circuit breaker</span>
            </div>
          </div>
        </div>
      )
    },
    {
      q: 'How did the PUCSL January 18, 2025 tariff revision affect solar economics?',
      a: (
        <div className="space-y-2 text-xs text-slate-600 leading-relaxed">
          <p>
            Under the PUCSL Tariff Revision effective January 18, 2025, domestic consumers face progressive block tariffs up to <b>52.00 LKR/kWh</b> for units above 180 kWh/month.
          </p>
          <p>
            Because rooftop solar eliminates consumption from the highest tariff blocks first, solar owners experience substantial bill reductions. A household consuming 250–350 units saves over <b>LKR 11,000 to 17,000 each month</b>, enabling rapid simple payback within <b>3.0 to 4.2 years</b>.
          </p>
        </div>
      )
    },
    {
      q: 'What is PUCSL Condition 3 regarding solar prosumer fixed charges?',
      a: (
        <div className="space-y-2 text-xs text-slate-600 leading-relaxed">
          <p>
            In Annex 2 of the January 2025 Decision Document, the PUCSL ordered: <i>"Fixed charges for solar prosumers shall be based on the net consumption."</i>
          </p>
          <p>
            This means that if your rooftop solar system offsets your entire monthly usage so that your net import is 0 kWh, your utility fixed monthly charge drops to <b>LKR 0.00</b> (instead of the LKR 2,000 monthly charge otherwise applied to high-tier consumers). SolarCalc LK V1.0 strictly implements this rule.
          </p>
        </div>
      )
    },
    {
      q: 'What is the capacity limit for a single-phase residential grid connection?',
      a: (
        <div className="space-y-2 text-xs text-slate-600 leading-relaxed">
          <p>
            Under CEB/LECO distribution guidelines, single-phase 230V residential connections have a solar inverter capacity ceiling of <b>5 kW (approx. 5.2 kWp DC)</b>.
          </p>
          <p>
            For solar arrays larger than 5 kW, the utility requires a <b>Three-Phase 400V</b> electricity connection. SolarCalc LK automatically selects single-phase inverters for ≤ 5 kW systems and transitions to three-phase string inverters for larger systems.
          </p>
        </div>
      )
    },
    {
      q: 'Do I need a battery storage system (BESS) for residential rooftop solar?',
      a: (
        <div className="space-y-2 text-xs text-slate-600 leading-relaxed">
          <p>
            For a standard grid-connected system under Net Accounting or Net Metering, <b>batteries are not required</b>. The CEB national grid acts as a virtual battery—absorbing daytime excess solar and supplying nighttime household loads.
          </p>
          <p>
            Batteries are primarily beneficial if you require backup power during grid power cuts or if future Time-of-Use (TOU) tariffs make peak-shaving economically viable. SolarCalc LK supports hybrid battery-ready inverter configurations for future expansion.
          </p>
        </div>
      )
    },
    {
      q: 'What are the required approvals before installing rooftop solar in Sri Lanka?',
      a: (
        <div className="space-y-2 text-xs text-slate-600 leading-relaxed">
          <ol className="list-decimal list-inside space-y-1 pl-2">
            <li><b>Initial Assessment:</b> Use SolarCalc LK to determine optimal system capacity.</li>
            <li><b>SLSEA Registered Installer:</b> Contract an installer accredited by the Sri Lanka Sustainable Energy Authority (SLSEA).</li>
            <li><b>CEB/LECO Interconnection Application:</b> Submit the RTSPV application form with inverter type-test certificates and a single-line electrical diagram (SLD).</li>
            <li><b>Site Testing & Metering:</b> Utility engineers inspect the installation and install a bidirectional smart meter.</li>
            <li><b>Agreement Execution:</b> Sign the 20-year Standardized Power Purchase Agreement (SPPA).</li>
          </ol>
        </div>
      )
    },
    {
      q: 'What warranties should I look for when purchasing equipment?',
      a: (
        <div className="space-y-2 text-xs text-slate-600 leading-relaxed">
          <p>According to PUCSL Guidelines Revision 1, homeowners should insist on:</p>
          <ul className="list-disc list-inside space-y-1 pl-2">
            <li><b>PV Modules:</b> Minimum 12–15 years product warranty and 25–30 years linear performance warranty (guaranteeing ≥ 84% output at Year 25).</li>
            <li><b>String Inverters:</b> Minimum 5-year standard warranty (expandable to 10 years).</li>
            <li><b>Mounting Structures:</b> Minimum 10 years anti-corrosion warranty on anodized aluminum or stainless steel hardware.</li>
          </ul>
        </div>
      )
    }
  ];

  return (
    <div className="space-y-8 max-w-4xl mx-auto">
      <div>
        <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-amber-100 text-amber-900 border border-amber-200 text-xs font-bold mb-2">
          <HelpCircle className="w-3.5 h-3.5 text-amber-600" />
          <span>Frequently Asked Questions</span>
        </div>
        <h1 className="text-2xl sm:text-4xl font-black text-slate-900 tracking-tight">
          Sri Lankan Rooftop Solar FAQ & Guidance
        </h1>
        <p className="text-xs sm:text-sm text-slate-600 mt-1">
          Essential answers regarding PUCSL electricity tariffs, CEB grid interconnection, warranties, and rooftop solar economics.
        </p>
      </div>

      <div className="space-y-3">
        {faqs.map((faq, idx) => {
          const isOpen = openIdx === idx;
          return (
            <div
              key={idx}
              className="bg-white rounded-2xl border border-slate-200 overflow-hidden shadow-xs transition-all"
            >
              <button
                onClick={() => setOpenIdx(isOpen ? null : idx)}
                className="w-full p-5 text-left flex items-center justify-between gap-4 hover:bg-slate-50 transition-colors"
              >
                <span className="font-bold text-sm text-slate-900 flex items-center gap-2.5">
                  <span className="w-6 h-6 rounded-lg bg-slate-100 text-slate-600 text-xs flex items-center justify-center shrink-0 font-mono">
                    {idx + 1}
                  </span>
                  {faq.q}
                </span>
                {isOpen ? (
                  <ChevronUp className="w-4 h-4 text-slate-400 shrink-0" />
                ) : (
                  <ChevronDown className="w-4 h-4 text-slate-400 shrink-0" />
                )}
              </button>

              {isOpen && (
                <div className="px-5 pb-5 pt-1 border-t border-slate-100 bg-slate-50/50">
                  {faq.a}
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
};
