import React from 'react';
import { ShieldAlert, Scale, AlertTriangle, FileCheck, CheckCircle2 } from 'lucide-react';

export const TermsPage: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto space-y-8 py-4">
      {/* Header */}
      <div>
        <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-amber-100 text-amber-900 border border-amber-200 text-xs font-bold mb-2">
          <Scale className="w-3.5 h-3.5 text-amber-600" />
          <span>Terms of Use & Legal Disclaimers</span>
        </div>
        <h1 className="text-2xl sm:text-4xl font-black text-slate-900 tracking-tight">
          Terms of Service & Engineering Disclaimer
        </h1>
        <p className="text-xs sm:text-sm text-slate-600 mt-1">
          Version 1.0 • Sri Lanka Energy Regulatory Compliance
        </p>
      </div>

      {/* Prominent Disclaimer Card */}
      <div className="bg-amber-50/80 border-2 border-amber-300/80 rounded-2xl p-6 shadow-xs flex items-start gap-4">
        <ShieldAlert className="w-8 h-8 text-amber-600 shrink-0 mt-1" />
        <div className="space-y-2">
          <h3 className="font-bold text-amber-950 text-base">
            Mandatory Engineering Notice
          </h3>
          <p className="text-xs sm:text-sm text-amber-900 leading-relaxed">
            SolarCalc LK V1.0 provides preliminary planning models, solar resource yield estimates, and financial projections. 
            <b> This web application is NOT a certified engineering design, site survey, structural evaluation, utility grid approval, or commercial contract quotation.</b>
          </p>
        </div>
      </div>

      {/* Terms Sections */}
      <div className="bg-white rounded-2xl border border-slate-200 p-8 shadow-xs space-y-6 text-sm text-slate-700 leading-relaxed">
        <section className="space-y-2">
          <h2 className="text-base font-bold text-slate-900 flex items-center gap-2">
            <CheckCircle2 className="w-4 h-4 text-amber-600" />
            1. Scope of the Application
          </h2>
          <p className="text-xs sm:text-sm text-slate-600">
            SolarCalc LK is created for educational, research, and pre-feasibility decision support for residential homeowners and clean energy advocates in Sri Lanka. It models rooftop PV system behavior according to standard mathematical formulas and verified benchmark documents published by the Public Utilities Commission of Sri Lanka (PUCSL) and the Ceylon Electricity Board (CEB).
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-bold text-slate-900 flex items-center gap-2">
            <CheckCircle2 className="w-4 h-4 text-amber-600" />
            2. Site-Specific Conditions & Limitations
          </h2>
          <p className="text-xs sm:text-sm text-slate-600">
            Real-world performance may diverge from the models due to:
          </p>
          <ul className="list-disc pl-5 text-xs sm:text-sm text-slate-600 space-y-1 mt-2">
            <li>Localized shading caused by nearby trees, buildings, parapet walls, or utility poles.</li>
            <li>Microclimatic variance, severe monsoon precipitation, or unmodeled coastal salt mist corrosion.</li>
            <li>Roof structural capacity, purlin degradation, or inadequate rafter anchorage.</li>
            <li>Local CEB or LECO distribution transformer capacity constraints or voltage rise limits.</li>
          </ul>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-bold text-slate-900 flex items-center gap-2">
            <CheckCircle2 className="w-4 h-4 text-amber-600" />
            3. Tariff and Regulatory Volatility
          </h2>
          <p className="text-xs sm:text-sm text-slate-600">
            All bill calculations model the <b>PUCSL Final Decision Document on Electricity Tariff Revision (Effective January 18, 2025)</b> and the CEB RTSPV Feed-in Tariff of 44.14 LKR/kWh. Utility tariff schedules and export policies are subject to periodic regulatory review by the PUCSL and may change during the 20-year lifetime of a solar PV asset.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-bold text-slate-900 flex items-center gap-2">
            <CheckCircle2 className="w-4 h-4 text-amber-600" />
            4. Limitation of Liability
          </h2>
          <p className="text-xs sm:text-sm text-slate-600">
            Under no circumstances shall the author (Farhan Mohammad) or the Faculty of Engineering, University of Jaffna, be held liable for any direct, indirect, consequential, or financial losses arising from investment decisions, equipment procurement, or contractual commitments made in reliance upon calculations generated by SolarCalc LK. Users must engage certified solar contractors registered with the Sri Lanka Sustainable Energy Authority (SLSEA).
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-base font-bold text-slate-900 flex items-center gap-2">
            <CheckCircle2 className="w-4 h-4 text-amber-600" />
            5. Intellectual Property & Attribution
          </h2>
          <p className="text-xs sm:text-sm text-slate-600">
            The algorithms, source code, and design architecture are developed and maintained by <b>Farhan Mohammad</b>. The underlying datasets remain the property of their respective creators (World Bank Global Solar Atlas, PUCSL, and CEB).
          </p>
        </section>
      </div>
    </div>
  );
};
